export const PROVIDER = 'kimi-subscription'
export const DISPLAY_NAME = 'Kimi subscription'
export const CHANNEL = '/kimi-subscription'
export const CREDENTIAL_NAME = 'KIMI_CODE_SUBSCRIPTION_CREDENTIAL'
export const PACKAGE_VERSION = '0.1.0'
